"""knowledge_sync — carry review-verified knowledge between DPE runs on a repo.

Runs as a tool STEP near the end of the pipeline (after the final verifier +
deterministic gates, before the final review). It distills already-produced,
review-adjacent artifacts — the architecture design (post architecture-review)
and the final verify report (post final-verifier) — into a single git-IGNORED
file in the project repo:

    <repo>/.aitelier/knowledge.md

The next run's Researcher reads this file (a `from: repository` context source),
so it starts with the prior run's wisdom WITHOUT being handed raw failure
transcripts: only the design summary, what the verifier confirmed works, and the
issues it flagged (explicitly labelled as "known issues / pitfalls").

Design choices that keep this safe and simple:
  - **Git-ignored, not committed.** The file is added to ``.git/info/exclude``
    (the per-clone, untracked ignore list) so it never pollutes the user's repo,
    never shows in diffs/PRs, and `repo_apply`'s ``git add`` skips it. Corrupt
    it? ``rm -rf .aitelier`` — that's the whole recovery story.
  - **Deterministic, no extra LLM call.** Assembled from files already on disk;
    no DeepSeek cost.
  - **One section per project, deduped.** A run rewrites its own section (so the
    goal-loop's repeated passes don't pile up); newest ``_MAX_SECTIONS`` kept.
  - **Never raises.** A bad/missing artifact degrades to "wrote nothing".
"""

import json
import re
from datetime import date
from pathlib import Path

_KNOWLEDGE_REL = Path(".aitelier") / "knowledge.md"
_EXCLUDE_LINE = ".aitelier/"
_MARKER = "<!-- aitelier:run pid={pid} -->"
_MARKER_RE = re.compile(r"^<!-- aitelier:run pid=(?P<pid>.+?) -->$", re.MULTILINE)
_MAX_SECTIONS = 5
_HEADER = (
    "# AItelier — cross-run knowledge (git-ignored, safe to delete)\n\n"
    "Auto-generated by the DPE pipeline to carry distilled, review-verified\n"
    "knowledge between runs on this repo. NOT committed. Delete freely if stale.\n"
)


def knowledge_sync(*, project_root: str = "", workspace_root: str = "",
                   config_name: str = "", project_id: str = "",
                   out_dir: str = "", **kwargs) -> dict:
    """Distill this run's knowledge into <repo>/.aitelier/knowledge.md.

    Returns {written: bool, path, section, reason}. Always succeeds.
    """
    try:
        repo = Path(project_root).resolve() if project_root else None
        if not repo or not repo.exists():
            return {"written": False, "reason": f"repo not found: {project_root}"}

        pid = project_id or (Path(workspace_root).name if workspace_root else "run")
        graph_dir = _locate_graph_dir(workspace_root, config_name, out_dir)

        section = _build_section(pid, graph_dir)
        if section is None:
            return {"written": False,
                    "reason": "no distillable artifacts (design/verify) found"}

        # Ensure the file is ignored BEFORE writing it, so a concurrent git add
        # never stages it.
        _ensure_excluded(repo)

        kpath = repo / _KNOWLEDGE_REL
        kpath.parent.mkdir(parents=True, exist_ok=True)
        existing = kpath.read_text(encoding="utf-8", errors="replace") \
            if kpath.exists() else ""
        merged = _merge(existing, pid, section)
        kpath.write_text(merged, encoding="utf-8")
        return {"written": True, "path": str(kpath), "section": pid}
    except Exception as e:  # a knowledge write must never fail the run
        return {"written": False, "reason": f"error: {e}"}


# ── Distillation ──────────────────────────────────────────────────────────

def _locate_graph_dir(workspace_root: str, config_name: str,
                      out_dir: str) -> Path | None:
    """Directory holding the per-step output dirs (sibling '2', '5', ...)."""
    if workspace_root and config_name:
        d = Path(workspace_root) / config_name
        if d.exists():
            return d
    if out_dir:  # $STEP_DIR → parent is the graph dir
        p = Path(out_dir).parent
        if p.exists():
            return p
    return None


def _build_section(pid: str, graph_dir: Path | None) -> str | None:
    """Assemble one markdown section from design + verify artifacts.

    Returns None if neither artifact is present (nothing worth recording).
    """
    if graph_dir is None:
        return None

    design = _read_text(graph_dir / "2" / "step2_design.md")
    report = _read_json(graph_dir / "5" / "final" / "verify_report.json")
    if not design and not report:
        return None

    lines = [_MARKER.format(pid=pid), f"## {pid} — {date.today().isoformat()}", ""]

    if report:
        met = report.get("all_goals_met")
        deploy = report.get("ready_for_deploy")
        lines.append(f"**Outcome:** goals_met={_b(met)} · ready_for_deploy={_b(deploy)}")
        verified = [str(s) for s in (report.get("verified_subtasks") or [])]
        if verified:
            lines.append(f"**Verified working:** {', '.join(verified)}")
        issues = [str(s) for s in (report.get("issues") or [])]
        if issues:
            lines.append("")
            lines.append("**Known issues / pitfalls (final review — avoid repeating):**")
            lines.extend(f"- {i}" for i in issues)

    if design:
        lines.append("")
        lines.append("**Architecture (from approved design):**")
        lines.append(_design_summary(design))

    return "\n".join(lines).rstrip() + "\n"


def _design_summary(design: str, max_chars: int = 1400) -> str:
    """Overview paragraph (if any) + the design's section headers."""
    overview = _section_body(design, "Overview")
    headers = [m.group(2).strip()
               for m in re.finditer(r"^(#{2,3})\s+(.*)$", design, re.MULTILINE)]
    parts = []
    if overview:
        parts.append(overview.strip())
    if headers:
        parts.append("Sections: " + " · ".join(headers[:20]))
    text = "\n\n".join(parts).strip()
    if len(text) > max_chars:
        text = text[:max_chars].rstrip() + " …"
    return text or "(see step2_design.md)"


def _section_body(md: str, header: str) -> str:
    """Body text under a `## header` up to the next same/higher header."""
    m = re.search(rf"^#{{1,3}}\s+{re.escape(header)}\s*$", md, re.MULTILINE)
    if not m:
        return ""
    start = m.end()
    nxt = re.search(r"^#{1,3}\s+", md[start:], re.MULTILINE)
    body = md[start: start + nxt.start()] if nxt else md[start:]
    return body.strip()


# ── Merge / dedup ─────────────────────────────────────────────────────────

def _merge(existing: str, pid: str, section: str) -> str:
    """Drop any prior section for `pid`, prepend the new one, cap to N."""
    sections = _split_sections(existing)
    sections = [(p, body) for (p, body) in sections if p != pid]
    sections.insert(0, (pid, section))
    sections = sections[:_MAX_SECTIONS]
    body = "\n\n".join(s for _, s in sections).rstrip() + "\n"
    return _HEADER + "\n" + body


def _split_sections(text: str) -> list[tuple[str, str]]:
    """Split a knowledge file into (pid, section_text) by run markers."""
    if not text:
        return []
    matches = list(_MARKER_RE.finditer(text))
    out = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        out.append((m.group("pid"), text[start:end].strip()))
    return out


# ── Git ignore wiring ─────────────────────────────────────────────────────

def _ensure_excluded(repo: Path) -> None:
    """Append `.aitelier/` to .git/info/exclude (untracked, per-clone) once.

    Uses .git/info/exclude rather than the tracked .gitignore so we never modify
    a file the user owns / that shows up in their diff.
    """
    git_dir = repo / ".git"
    if not git_dir.exists():
        return
    # Worktrees/submodules: .git may be a file pointing at the real gitdir.
    if git_dir.is_file():
        try:
            ref = git_dir.read_text(encoding="utf-8").strip()
            if ref.startswith("gitdir:"):
                git_dir = Path(ref.split(":", 1)[1].strip())
                if not git_dir.is_absolute():
                    git_dir = (repo / git_dir).resolve()
        except Exception:
            return
    info = git_dir / "info"
    info.mkdir(parents=True, exist_ok=True)
    exclude = info / "exclude"
    current = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    if any(ln.strip() == _EXCLUDE_LINE for ln in current.splitlines()):
        return
    sep = "" if current.endswith("\n") or not current else "\n"
    exclude.write_text(
        current + sep + f"{_EXCLUDE_LINE}\n", encoding="utf-8")


# ── small helpers ─────────────────────────────────────────────────────────

def _read_text(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="replace") if p.exists() else ""
    except Exception:
        return ""


def _read_json(p: Path) -> dict | None:
    try:
        return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None
    except Exception:
        return None


def _b(v) -> str:
    return "true" if v is True else "false" if v is False else "unknown"
